port = 8080
camera_path = "/dev/video0"
username = "alexis"
pass_hash = "$argon2id$v=19$m=19456,t=2,p=1$+QuvOFPKg20XztjgaAszzA$riTV7qgYYrZ/IHbI/mhwLxWAjev2oqQsMqoNANwbzpI"
salt = "+QuvOFPKg20XztjgaAszzA"
